// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkegdnhblpaccdnwwlba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrZWdkbmhibHBhY2Nkbnd3bGJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NTkzMDgsImV4cCI6MjA3MjIzNTMwOH0.R4Anb2bBZFDEA5cfSM0PkYdAHrbRhSmwCcFac-oX-6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});